# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'billQdialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(840, 535)
        Dialog.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cbBillType = QtGui.QComboBox(Dialog)
        self.cbBillType.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.cbBillType.setObjectName(_fromUtf8("cbBillType"))
        self.cbBillType.addItem(_fromUtf8(""))
        self.cbBillType.addItem(_fromUtf8(""))
        self.cbBillType.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbBillType)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.cbBillStyle = QtGui.QComboBox(Dialog)
        self.cbBillStyle.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.cbBillStyle.setObjectName(_fromUtf8("cbBillStyle"))
        self.cbBillStyle.addItem(_fromUtf8(""))
        self.cbBillStyle.addItem(_fromUtf8(""))
        self.cbBillStyle.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.cbBillStyle)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.toolBox = QtGui.QToolBox(self.page)
        self.toolBox.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 804, 271))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(35, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.leCity = QtGui.QLineEdit(self.page_5)
        self.leCity.setObjectName(_fromUtf8("leCity"))
        self.horizontalLayout_4.addWidget(self.leCity)
        self.label_4 = QtGui.QLabel(self.page_5)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.deCreationDate = QtGui.QDateEdit(self.page_5)
        self.deCreationDate.setMinimumSize(QtCore.QSize(100, 0))
        self.deCreationDate.setObjectName(_fromUtf8("deCreationDate"))
        self.horizontalLayout_4.addWidget(self.deCreationDate)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(35, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.leProduct = QtGui.QLineEdit(self.page_5)
        self.leProduct.setObjectName(_fromUtf8("leProduct"))
        self.horizontalLayout_5.addWidget(self.leProduct)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.page_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.leNumBill = QtGui.QLineEdit(self.page_5)
        self.leNumBill.setObjectName(_fromUtf8("leNumBill"))
        self.horizontalLayout_2.addWidget(self.leNumBill)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(35, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.leClientName = QtGui.QLineEdit(self.page_5)
        self.leClientName.setObjectName(_fromUtf8("leClientName"))
        self.horizontalLayout_3.addWidget(self.leClientName)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 787, 364))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.checkBox_5 = QtGui.QCheckBox(self.page_6)
        self.checkBox_5.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout_14.addWidget(self.checkBox_5)
        self.billFontComboBox = QtGui.QFontComboBox(self.page_6)
        self.billFontComboBox.setObjectName(_fromUtf8("billFontComboBox"))
        self.horizontalLayout_14.addWidget(self.billFontComboBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.label_14 = QtGui.QLabel(self.page_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.billFontSize = QtGui.QSpinBox(self.page_6)
        self.billFontSize.setObjectName(_fromUtf8("billFontSize"))
        self.horizontalLayout_14.addWidget(self.billFontSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_4 = QtGui.QCheckBox(self.page_6)
        self.checkBox_4.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_10.addWidget(self.checkBox_4)
        self.lineEdit_6 = QtGui.QLineEdit(self.page_6)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.toolButton_2 = QtGui.QToolButton(self.page_6)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout_10.addWidget(self.toolButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox = QtGui.QCheckBox(self.page_6)
        self.checkBox.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.lineEdit = QtGui.QLineEdit(self.page_6)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.toolButton = QtGui.QToolButton(self.page_6)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_6.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBox_3 = QtGui.QCheckBox(self.page_6)
        self.checkBox_3.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_9.addWidget(self.checkBox_3)
        self.textEdit_2 = QtGui.QTextEdit(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.horizontalLayout_9.addWidget(self.textEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_2 = QtGui.QCheckBox(self.page_6)
        self.checkBox_2.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.textEdit = QtGui.QTextEdit(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_7.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 90, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 787, 333))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        spacerItem4 = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_17.addItem(spacerItem4)
        self.toolButton_3 = QtGui.QToolButton(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMaximumSize(QtCore.QSize(26, 23))
        self.toolButton_3.setStyleSheet(_fromUtf8("QToolButton{/*\n"
"    color: rgb(227, 238, 238);*/\n"
"    font: 75 18pt \"Gill Sans MT\";\n"
"    background-color: rgba(0,0,0,0);\n"
"}"))
        self.toolButton_3.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_3.setAutoRaise(False)
        self.toolButton_3.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.verticalLayout_17.addWidget(self.toolButton_3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_17)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_8.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.cbBillCat = QtGui.QComboBox(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbBillCat.sizePolicy().hasHeightForWidth())
        self.cbBillCat.setSizePolicy(sizePolicy)
        self.cbBillCat.setMinimumSize(QtCore.QSize(80, 0))
        self.cbBillCat.setMaximumSize(QtCore.QSize(16777215, 23))
        self.cbBillCat.setObjectName(_fromUtf8("cbBillCat"))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.cbBillCat.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cbBillCat)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_9 = QtGui.QLabel(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_9.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_12.addWidget(self.label_9)
        self.deItemDate = QtGui.QDateEdit(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deItemDate.sizePolicy().hasHeightForWidth())
        self.deItemDate.setSizePolicy(sizePolicy)
        self.deItemDate.setMinimumSize(QtCore.QSize(56, 0))
        self.deItemDate.setMaximumSize(QtCore.QSize(120, 23))
        self.deItemDate.setObjectName(_fromUtf8("deItemDate"))
        self.verticalLayout_12.addWidget(self.deItemDate)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_10 = QtGui.QLabel(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_10.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_13.addWidget(self.label_10)
        self.lineEdit_7 = QtGui.QLineEdit(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(70, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(16777215, 23))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.verticalLayout_13.addWidget(self.lineEdit_7)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_11 = QtGui.QLabel(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_11.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_14.addWidget(self.label_11)
        self.sbItemQty = QtGui.QSpinBox(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbItemQty.sizePolicy().hasHeightForWidth())
        self.sbItemQty.setSizePolicy(sizePolicy)
        self.sbItemQty.setMaximumSize(QtCore.QSize(50, 23))
        self.sbItemQty.setObjectName(_fromUtf8("sbItemQty"))
        self.verticalLayout_14.addWidget(self.sbItemQty)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_12 = QtGui.QLabel(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_12.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_15.addWidget(self.label_12)
        self.leUnitPrice = QtGui.QLineEdit(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leUnitPrice.sizePolicy().hasHeightForWidth())
        self.leUnitPrice.setSizePolicy(sizePolicy)
        self.leUnitPrice.setMinimumSize(QtCore.QSize(70, 0))
        self.leUnitPrice.setMaximumSize(QtCore.QSize(16777215, 23))
        self.leUnitPrice.setObjectName(_fromUtf8("leUnitPrice"))
        self.verticalLayout_15.addWidget(self.leUnitPrice)
        self.horizontalLayout_13.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_13 = QtGui.QLabel(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label_13.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_16.addWidget(self.label_13)
        self.btnNewC_2 = QtGui.QPushButton(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewC_2.sizePolicy().hasHeightForWidth())
        self.btnNewC_2.setSizePolicy(sizePolicy)
        self.btnNewC_2.setMinimumSize(QtCore.QSize(81, 0))
        self.btnNewC_2.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnNewC_2.setFont(font)
        self.btnNewC_2.setToolTip(_fromUtf8(""))
        self.btnNewC_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnNewC_2.setAutoFillBackground(False)
        self.btnNewC_2.setStyleSheet(_fromUtf8(""))
        self.btnNewC_2.setFlat(False)
        self.btnNewC_2.setObjectName(_fromUtf8("btnNewC_2"))
        self.verticalLayout_16.addWidget(self.btnNewC_2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_16)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.tableView_2 = QtGui.QTableView(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_2.sizePolicy().hasHeightForWidth())
        self.tableView_2.setSizePolicy(sizePolicy)
        self.tableView_2.setMinimumSize(QtCore.QSize(0, 250))
        self.tableView_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.horizontalLayout_12.addWidget(self.tableView_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btnEditC_2 = QtGui.QPushButton(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditC_2.sizePolicy().hasHeightForWidth())
        self.btnEditC_2.setSizePolicy(sizePolicy)
        self.btnEditC_2.setMinimumSize(QtCore.QSize(81, 0))
        self.btnEditC_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btnEditC_2.setDefault(False)
        self.btnEditC_2.setFlat(False)
        self.btnEditC_2.setObjectName(_fromUtf8("btnEditC_2"))
        self.verticalLayout_3.addWidget(self.btnEditC_2)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem5)
        self.btnDelC_2 = QtGui.QPushButton(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelC_2.sizePolicy().hasHeightForWidth())
        self.btnDelC_2.setSizePolicy(sizePolicy)
        self.btnDelC_2.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btnDelC_2.setStyleSheet(_fromUtf8("\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(255, 54, 54, 255), stop:1 rgba(100, 0, 0, 255));\n"
"    border-style: outset;\n"
"    border-top-color: rgb(180, 54, 54);\n"
"    border-left-color: rgb(180, 54, 54);\n"
"    border-right-color: rgb(180, 54, 54);\n"
"    border-bottom-color: rgb(100, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(100, 0, 0);\n"
"    border-style: inset;\n"
"    border-color:rgb(100, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton:!enabled {\n"
"    border-color:rgb(15, 32, 54);\n"
"    border-style: outset;\n"
"}"))
        self.btnDelC_2.setObjectName(_fromUtf8("btnDelC_2"))
        self.verticalLayout_3.addWidget(self.btnDelC_2)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 804, 271))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.webView = QtWebKit.QWebView(self.page_3)
        self.webView.setStyleSheet(_fromUtf8("background-color: rgb(227, 238, 238);"))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("google.com")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout.addWidget(self.webView)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.toolBox, 2, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 1, 0, 1, 1)
        self.frameBillDia = QtGui.QFrame(self.page)
        self.frameBillDia.setStyleSheet(_fromUtf8("QFrame{\n"
"    border-top: 1px solid rgba(227, 238, 238,200);\n"
"\n"
"}"))
        self.frameBillDia.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBillDia.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBillDia.setObjectName(_fromUtf8("frameBillDia"))
        self.gridLayout_5.addWidget(self.frameBillDia, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.rbLatex = QtGui.QRadioButton(Dialog)
        self.rbLatex.setObjectName(_fromUtf8("rbLatex"))
        self.horizontalLayout_15.addWidget(self.rbLatex)
        self.rbWord = QtGui.QRadioButton(Dialog)
        self.rbWord.setObjectName(_fromUtf8("rbWord"))
        self.horizontalLayout_15.addWidget(self.rbWord)
        self.btnGenPreview = QtGui.QPushButton(Dialog)
        self.btnGenPreview.setObjectName(_fromUtf8("btnGenPreview"))
        self.horizontalLayout_15.addWidget(self.btnGenPreview)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_15.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.stackedWidget.raise_()

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(3)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Select type of bill from box: ", None))
        self.cbBillType.setItemText(0, _translate("Dialog", "New", None))
        self.cbBillType.setItemText(1, _translate("Dialog", "New from Job", None))
        self.cbBillType.setItemText(2, _translate("Dialog", "New from Client", None))
        self.label_7.setText(_translate("Dialog", "Select style from box: ", None))
        self.cbBillStyle.setItemText(0, _translate("Dialog", "Kiwi Green", None))
        self.cbBillStyle.setItemText(1, _translate("Dialog", "Kiwi B&W", None))
        self.cbBillStyle.setItemText(2, _translate("Dialog", "Custom...", None))
        self.label_3.setText(_translate("Dialog", "Ville:", None))
        self.label_4.setText(_translate("Dialog", "Le:", None))
        self.label_6.setText(_translate("Dialog", "Produit", None))
        self.label_2.setText(_translate("Dialog", "NUMERO FACTURE", None))
        self.label_5.setText(_translate("Dialog", "Client", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Dialog", "Information", None))
        self.checkBox_5.setText(_translate("Dialog", "Set Font", None))
        self.label_14.setText(_translate("Dialog", "Size", None))
        self.checkBox_4.setText(_translate("Dialog", "Header Image", None))
        self.toolButton_2.setText(_translate("Dialog", "...", None))
        self.checkBox.setText(_translate("Dialog", "Footer Image", None))
        self.toolButton.setText(_translate("Dialog", "...", None))
        self.checkBox_3.setText(_translate("Dialog", "Header Text", None))
        self.checkBox_2.setText(_translate("Dialog", "Footer Text", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("Dialog", "Format", None))
        self.toolButton_3.setText(_translate("Dialog", "+", None))
        self.label_8.setText(_translate("Dialog", "Category", None))
        self.cbBillCat.setItemText(0, _translate("Dialog", "<Select Category>", None))
        self.cbBillCat.setItemText(1, _translate("Dialog", "Couverture Evenement", None))
        self.cbBillCat.setItemText(2, _translate("Dialog", "Shooting Photo", None))
        self.cbBillCat.setItemText(3, _translate("Dialog", "Shooting Video", None))
        self.cbBillCat.setItemText(4, _translate("Dialog", "Shooting Photo-Video", None))
        self.cbBillCat.setItemText(5, _translate("Dialog", "Packshot Produit", None))
        self.cbBillCat.setItemText(6, _translate("Dialog", "3D Conception (Stand)", None))
        self.cbBillCat.setItemText(7, _translate("Dialog", "3D Conception (Objet, Model, Structure)", None))
        self.cbBillCat.setItemText(8, _translate("Dialog", "2D Conception Logo", None))
        self.cbBillCat.setItemText(9, _translate("Dialog", "2D Conception Maquette (Vectoriel, Bitmap)", None))
        self.label_9.setText(_translate("Dialog", "Date", None))
        self.label_10.setText(_translate("Dialog", "Description", None))
        self.lineEdit_7.setText(_translate("Dialog", "<Description>", None))
        self.label_11.setText(_translate("Dialog", "Quantity", None))
        self.label_12.setText(_translate("Dialog", "Price/Unit", None))
        self.leUnitPrice.setText(_translate("Dialog", "<Description>", None))
        self.btnNewC_2.setText(_translate("Dialog", "Add", None))
        self.btnEditC_2.setText(_translate("Dialog", "Edit", None))
        self.btnDelC_2.setText(_translate("Dialog", "Delete", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("Dialog", "Detail", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Dialog", "Preview", None))
        self.rbLatex.setText(_translate("Dialog", "LaTeX", None))
        self.rbWord.setText(_translate("Dialog", "MS Word", None))
        self.btnGenPreview.setText(_translate("Dialog", "Preview PDF", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

