# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'billQdialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(696, 703)
        Dialog.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cbBillType = QtGui.QComboBox(Dialog)
        self.cbBillType.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.cbBillType.setObjectName(_fromUtf8("cbBillType"))
        self.cbBillType.addItem(_fromUtf8(""))
        self.cbBillType.addItem(_fromUtf8(""))
        self.cbBillType.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbBillType)
        self.horizontalLayout_11.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.cbBillStyle = QtGui.QComboBox(Dialog)
        self.cbBillStyle.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.cbBillStyle.setObjectName(_fromUtf8("cbBillStyle"))
        self.cbBillStyle.addItem(_fromUtf8(""))
        self.cbBillStyle.addItem(_fromUtf8(""))
        self.cbBillStyle.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.cbBillStyle)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.rbLatex = QtGui.QRadioButton(Dialog)
        self.rbLatex.setObjectName(_fromUtf8("rbLatex"))
        self.horizontalLayout_15.addWidget(self.rbLatex)
        self.rbWord = QtGui.QRadioButton(Dialog)
        self.rbWord.setObjectName(_fromUtf8("rbWord"))
        self.horizontalLayout_15.addWidget(self.rbWord)
        self.btnGenPreview = QtGui.QPushButton(Dialog)
        self.btnGenPreview.setObjectName(_fromUtf8("btnGenPreview"))
        self.horizontalLayout_15.addWidget(self.btnGenPreview)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout_15.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.frameBillDia = QtGui.QFrame(self.page)
        self.frameBillDia.setStyleSheet(_fromUtf8("QFrame{\n"
"    border-top: 1px solid rgba(227, 238, 238,200);\n"
"\n"
"}"))
        self.frameBillDia.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameBillDia.setFrameShadow(QtGui.QFrame.Raised)
        self.frameBillDia.setObjectName(_fromUtf8("frameBillDia"))
        self.gridLayout_5.addWidget(self.frameBillDia, 0, 0, 1, 1)
        self.toolBox = QtGui.QToolBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setStyleSheet(_fromUtf8("font: 75 10pt \"Roboto\";"))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 660, 439))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(35, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.leClientName = QtGui.QLineEdit(self.page_5)
        self.leClientName.setObjectName(_fromUtf8("leClientName"))
        self.horizontalLayout_3.addWidget(self.leClientName)
        self.frameOkClientName = QtGui.QFrame(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameOkClientName.sizePolicy().hasHeightForWidth())
        self.frameOkClientName.setSizePolicy(sizePolicy)
        self.frameOkClientName.setMinimumSize(QtCore.QSize(24, 24))
        self.frameOkClientName.setStyleSheet(_fromUtf8("height: 48px;\n"
"width: 48px;\n"
"image: url(:/resources/icons/OK.png);"))
        self.frameOkClientName.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOkClientName.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOkClientName.setObjectName(_fromUtf8("frameOkClientName"))
        self.horizontalLayout_3.addWidget(self.frameOkClientName)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(35, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.leProduct = QtGui.QLineEdit(self.page_5)
        self.leProduct.setObjectName(_fromUtf8("leProduct"))
        self.horizontalLayout_5.addWidget(self.leProduct)
        self.frameOkProduct = QtGui.QFrame(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameOkProduct.sizePolicy().hasHeightForWidth())
        self.frameOkProduct.setSizePolicy(sizePolicy)
        self.frameOkProduct.setMinimumSize(QtCore.QSize(24, 24))
        self.frameOkProduct.setStyleSheet(_fromUtf8("height: 48px;\n"
"width: 48px;\n"
"image: url(:/resources/icons/OK.png);"))
        self.frameOkProduct.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOkProduct.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOkProduct.setObjectName(_fromUtf8("frameOkProduct"))
        self.horizontalLayout_5.addWidget(self.frameOkProduct)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.page_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.leNumBill = QtGui.QLineEdit(self.page_5)
        self.leNumBill.setObjectName(_fromUtf8("leNumBill"))
        self.horizontalLayout_2.addWidget(self.leNumBill)
        self.frameOkNumBill = QtGui.QFrame(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameOkNumBill.sizePolicy().hasHeightForWidth())
        self.frameOkNumBill.setSizePolicy(sizePolicy)
        self.frameOkNumBill.setMinimumSize(QtCore.QSize(24, 24))
        self.frameOkNumBill.setStyleSheet(_fromUtf8("height: 48px;\n"
"width: 48px;\n"
"image: url(:/resources/icons/OK.png);\n"
""))
        self.frameOkNumBill.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOkNumBill.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOkNumBill.setObjectName(_fromUtf8("frameOkNumBill"))
        self.horizontalLayout_2.addWidget(self.frameOkNumBill)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(35, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.leCity = QtGui.QLineEdit(self.page_5)
        self.leCity.setObjectName(_fromUtf8("leCity"))
        self.horizontalLayout_4.addWidget(self.leCity)
        self.frameOkCity = QtGui.QFrame(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameOkCity.sizePolicy().hasHeightForWidth())
        self.frameOkCity.setSizePolicy(sizePolicy)
        self.frameOkCity.setMinimumSize(QtCore.QSize(24, 24))
        self.frameOkCity.setStyleSheet(_fromUtf8("height: 48px;\n"
"width: 48px;\n"
"image: url(:/resources/icons/OK.png);"))
        self.frameOkCity.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOkCity.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOkCity.setObjectName(_fromUtf8("frameOkCity"))
        self.horizontalLayout_4.addWidget(self.frameOkCity)
        self.label_4 = QtGui.QLabel(self.page_5)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.deCreationDate = QtGui.QDateEdit(self.page_5)
        self.deCreationDate.setMinimumSize(QtCore.QSize(100, 0))
        self.deCreationDate.setObjectName(_fromUtf8("deCreationDate"))
        self.horizontalLayout_4.addWidget(self.deCreationDate)
        self.frameOkCreationDate = QtGui.QFrame(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameOkCreationDate.sizePolicy().hasHeightForWidth())
        self.frameOkCreationDate.setSizePolicy(sizePolicy)
        self.frameOkCreationDate.setMinimumSize(QtCore.QSize(24, 24))
        self.frameOkCreationDate.setStyleSheet(_fromUtf8("height: 48px;\n"
"width: 48px;\n"
"image: url(:/resources/icons/OK.png);"))
        self.frameOkCreationDate.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameOkCreationDate.setFrameShadow(QtGui.QFrame.Raised)
        self.frameOkCreationDate.setObjectName(_fromUtf8("frameOkCreationDate"))
        self.horizontalLayout_4.addWidget(self.frameOkCreationDate)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 4, 0, 1, 1)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 660, 439))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.checkBox_5 = QtGui.QCheckBox(self.page_6)
        self.checkBox_5.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.horizontalLayout_14.addWidget(self.checkBox_5)
        self.billFontComboBox = QtGui.QFontComboBox(self.page_6)
        self.billFontComboBox.setObjectName(_fromUtf8("billFontComboBox"))
        self.horizontalLayout_14.addWidget(self.billFontComboBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem3)
        self.label_14 = QtGui.QLabel(self.page_6)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_14.addWidget(self.label_14)
        self.billFontSize = QtGui.QSpinBox(self.page_6)
        self.billFontSize.setObjectName(_fromUtf8("billFontSize"))
        self.horizontalLayout_14.addWidget(self.billFontSize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.checkBox_4 = QtGui.QCheckBox(self.page_6)
        self.checkBox_4.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.horizontalLayout_10.addWidget(self.checkBox_4)
        self.lineEdit_6 = QtGui.QLineEdit(self.page_6)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_10.addWidget(self.lineEdit_6)
        self.toolButton_2 = QtGui.QToolButton(self.page_6)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout_10.addWidget(self.toolButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.checkBox = QtGui.QCheckBox(self.page_6)
        self.checkBox.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.lineEdit = QtGui.QLineEdit(self.page_6)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.toolButton = QtGui.QToolButton(self.page_6)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_6.addWidget(self.toolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.checkBox_3 = QtGui.QCheckBox(self.page_6)
        self.checkBox_3.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.horizontalLayout_9.addWidget(self.checkBox_3)
        self.textEdit_2 = QtGui.QTextEdit(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.horizontalLayout_9.addWidget(self.textEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.checkBox_2 = QtGui.QCheckBox(self.page_6)
        self.checkBox_2.setMinimumSize(QtCore.QSize(95, 0))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.horizontalLayout_7.addWidget(self.checkBox_2)
        self.textEdit = QtGui.QTextEdit(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_7.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 90, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 0, 1, 1)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.page_7 = QtGui.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 643, 476))
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter = QtGui.QSplitter(self.page_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtGui.QFrame.Raised)
        self.splitter.setLineWidth(50)
        self.splitter.setMidLineWidth(40)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.framePlaceHolder = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePlaceHolder.sizePolicy().hasHeightForWidth())
        self.framePlaceHolder.setSizePolicy(sizePolicy)
        self.framePlaceHolder.setObjectName(_fromUtf8("framePlaceHolder"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.framePlaceHolder)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        spacerItem5 = QtGui.QSpacerItem(20, 23, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_17.addItem(spacerItem5)
        self.toolButton_3 = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMaximumSize(QtCore.QSize(26, 23))
        self.toolButton_3.setStyleSheet(_fromUtf8("QToolButton{/*\n"
"    color: rgb(227, 238, 238);*/\n"
"    font: 75 18pt \"Gill Sans MT\";\n"
"    background-color: rgba(0,0,0,0);\n"
"}"))
        self.toolButton_3.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_3.setAutoRaise(False)
        self.toolButton_3.setArrowType(QtCore.Qt.RightArrow)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.verticalLayout_17.addWidget(self.toolButton_3)
        self.horizontalLayout_13.addLayout(self.verticalLayout_17)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_8.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.cbItemCat = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbItemCat.sizePolicy().hasHeightForWidth())
        self.cbItemCat.setSizePolicy(sizePolicy)
        self.cbItemCat.setMinimumSize(QtCore.QSize(80, 0))
        self.cbItemCat.setMaximumSize(QtCore.QSize(16777215, 23))
        self.cbItemCat.setObjectName(_fromUtf8("cbItemCat"))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.cbItemCat.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cbItemCat)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(5)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_9.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_12.addWidget(self.label_9)
        self.deItemDateStart = QtGui.QDateEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deItemDateStart.sizePolicy().hasHeightForWidth())
        self.deItemDateStart.setSizePolicy(sizePolicy)
        self.deItemDateStart.setMinimumSize(QtCore.QSize(56, 0))
        self.deItemDateStart.setMaximumSize(QtCore.QSize(120, 23))
        self.deItemDateStart.setObjectName(_fromUtf8("deItemDateStart"))
        self.verticalLayout_12.addWidget(self.deItemDateStart)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setSpacing(5)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 20))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_16.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_18.addWidget(self.label_16)
        self.deItemDateEnd = QtGui.QDateEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deItemDateEnd.sizePolicy().hasHeightForWidth())
        self.deItemDateEnd.setSizePolicy(sizePolicy)
        self.deItemDateEnd.setMinimumSize(QtCore.QSize(56, 0))
        self.deItemDateEnd.setMaximumSize(QtCore.QSize(120, 23))
        self.deItemDateEnd.setObjectName(_fromUtf8("deItemDateEnd"))
        self.verticalLayout_18.addWidget(self.deItemDateEnd)
        self.horizontalLayout_13.addLayout(self.verticalLayout_18)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(5)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_10.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_13.addWidget(self.label_10)
        self.leItemDescription = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leItemDescription.sizePolicy().hasHeightForWidth())
        self.leItemDescription.setSizePolicy(sizePolicy)
        self.leItemDescription.setMinimumSize(QtCore.QSize(70, 0))
        self.leItemDescription.setMaximumSize(QtCore.QSize(16777215, 23))
        self.leItemDescription.setObjectName(_fromUtf8("leItemDescription"))
        self.verticalLayout_13.addWidget(self.leItemDescription)
        self.horizontalLayout_13.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setSpacing(5)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_11.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_14.addWidget(self.label_11)
        self.sbItemQty = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbItemQty.sizePolicy().hasHeightForWidth())
        self.sbItemQty.setSizePolicy(sizePolicy)
        self.sbItemQty.setMaximumSize(QtCore.QSize(50, 23))
        self.sbItemQty.setObjectName(_fromUtf8("sbItemQty"))
        self.verticalLayout_14.addWidget(self.sbItemQty)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setSpacing(5)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 23))
        self.label_12.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_15.addWidget(self.label_12)
        self.leItemUnitPrice = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leItemUnitPrice.sizePolicy().hasHeightForWidth())
        self.leItemUnitPrice.setSizePolicy(sizePolicy)
        self.leItemUnitPrice.setMinimumSize(QtCore.QSize(70, 0))
        self.leItemUnitPrice.setMaximumSize(QtCore.QSize(16777215, 23))
        self.leItemUnitPrice.setObjectName(_fromUtf8("leItemUnitPrice"))
        self.verticalLayout_15.addWidget(self.leItemUnitPrice)
        self.horizontalLayout_13.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setSpacing(5)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 26))
        self.label_13.setStyleSheet(_fromUtf8("QLabel {\n"
"\n"
"    background-color: rgba(0, 0, 0,0);\n"
"\n"
"}"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_16.addWidget(self.label_13)
        self.btnAddInvoiceItem = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddInvoiceItem.sizePolicy().hasHeightForWidth())
        self.btnAddInvoiceItem.setSizePolicy(sizePolicy)
        self.btnAddInvoiceItem.setMinimumSize(QtCore.QSize(81, 0))
        self.btnAddInvoiceItem.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Roboto"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAddInvoiceItem.setFont(font)
        self.btnAddInvoiceItem.setToolTip(_fromUtf8(""))
        self.btnAddInvoiceItem.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnAddInvoiceItem.setAutoFillBackground(False)
        self.btnAddInvoiceItem.setStyleSheet(_fromUtf8(""))
        self.btnAddInvoiceItem.setFlat(False)
        self.btnAddInvoiceItem.setObjectName(_fromUtf8("btnAddInvoiceItem"))
        self.verticalLayout_16.addWidget(self.btnAddInvoiceItem)
        self.horizontalLayout_13.addLayout(self.verticalLayout_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.invoiceItemsTable = QtGui.QTableView(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.invoiceItemsTable.sizePolicy().hasHeightForWidth())
        self.invoiceItemsTable.setSizePolicy(sizePolicy)
        self.invoiceItemsTable.setMinimumSize(QtCore.QSize(0, 0))
        self.invoiceItemsTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.invoiceItemsTable.setObjectName(_fromUtf8("invoiceItemsTable"))
        self.horizontalLayout_12.addWidget(self.invoiceItemsTable)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btnEditInvoiceItem = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditInvoiceItem.sizePolicy().hasHeightForWidth())
        self.btnEditInvoiceItem.setSizePolicy(sizePolicy)
        self.btnEditInvoiceItem.setMinimumSize(QtCore.QSize(81, 0))
        self.btnEditInvoiceItem.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btnEditInvoiceItem.setDefault(False)
        self.btnEditInvoiceItem.setFlat(False)
        self.btnEditInvoiceItem.setObjectName(_fromUtf8("btnEditInvoiceItem"))
        self.verticalLayout_3.addWidget(self.btnEditInvoiceItem)
        self.btnDelInvoiceItem = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelInvoiceItem.sizePolicy().hasHeightForWidth())
        self.btnDelInvoiceItem.setSizePolicy(sizePolicy)
        self.btnDelInvoiceItem.setMaximumSize(QtCore.QSize(16777215, 23))
        self.btnDelInvoiceItem.setStyleSheet(_fromUtf8("\n"
"QPushButton:hover:!pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(255, 54, 54, 255), stop:1 rgba(100, 0, 0, 255));\n"
"    border-style: outset;\n"
"    border-top-color: rgb(180, 54, 54);\n"
"    border-left-color: rgb(180, 54, 54);\n"
"    border-right-color: rgb(180, 54, 54);\n"
"    border-bottom-color: rgb(100, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(100, 0, 0);\n"
"    border-style: inset;\n"
"    border-color:rgb(100, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton:!enabled {\n"
"    border-color:rgb(15, 32, 54);\n"
"    border-style: outset;\n"
"}"))
        self.btnDelInvoiceItem.setObjectName(_fromUtf8("btnDelInvoiceItem"))
        self.verticalLayout_3.addWidget(self.btnDelInvoiceItem)
        spacerItem6 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Ignored)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.gridLayout_2.addWidget(self.splitter, 1, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.page_7)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.toolBox.addItem(self.page_7, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 660, 439))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.page_3)
        self.scrollArea.setStyleSheet(_fromUtf8("QScrollArea{\n"
"    border: 1px solid white;\n"
"}"))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 640, 419))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.framePreviewTable = QtGui.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePreviewTable.sizePolicy().hasHeightForWidth())
        self.framePreviewTable.setSizePolicy(sizePolicy)
        self.framePreviewTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.framePreviewTable.setFrameShadow(QtGui.QFrame.Raised)
        self.framePreviewTable.setObjectName(_fromUtf8("framePreviewTable"))
        self.gridLayoutPreviewTable = QtGui.QGridLayout(self.framePreviewTable)
        self.gridLayoutPreviewTable.setObjectName(_fromUtf8("gridLayoutPreviewTable"))
        self.label_30 = QtGui.QLabel(self.framePreviewTable)
        self.label_30.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayoutPreviewTable.addWidget(self.label_30, 1, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.framePreviewTable)
        self.label_27.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayoutPreviewTable.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.framePreviewTable)
        self.label_29.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayoutPreviewTable.addWidget(self.label_29, 1, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.framePreviewTable)
        self.label_28.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayoutPreviewTable.addWidget(self.label_28, 1, 1, 1, 1)
        self.seprLine1 = QtGui.QFrame(self.framePreviewTable)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seprLine1.sizePolicy().hasHeightForWidth())
        self.seprLine1.setSizePolicy(sizePolicy)
        self.seprLine1.setStyleSheet(_fromUtf8(""))
        self.seprLine1.setLineWidth(3)
        self.seprLine1.setFrameShape(QtGui.QFrame.HLine)
        self.seprLine1.setFrameShadow(QtGui.QFrame.Sunken)
        self.seprLine1.setObjectName(_fromUtf8("seprLine1"))
        self.gridLayoutPreviewTable.addWidget(self.seprLine1, 0, 0, 1, 4)
        self.sepLine2 = QtGui.QFrame(self.framePreviewTable)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sepLine2.sizePolicy().hasHeightForWidth())
        self.sepLine2.setSizePolicy(sizePolicy)
        self.sepLine2.setStyleSheet(_fromUtf8(""))
        self.sepLine2.setLineWidth(3)
        self.sepLine2.setFrameShape(QtGui.QFrame.HLine)
        self.sepLine2.setFrameShadow(QtGui.QFrame.Sunken)
        self.sepLine2.setObjectName(_fromUtf8("sepLine2"))
        self.gridLayoutPreviewTable.addWidget(self.sepLine2, 2, 0, 1, 4)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutPreviewTable.addItem(spacerItem7, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.framePreviewTable, 3, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_21.addWidget(self.label_25, QtCore.Qt.AlignHCenter)
        self.labelProduit = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProduit.sizePolicy().hasHeightForWidth())
        self.labelProduit.setSizePolicy(sizePolicy)
        self.labelProduit.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.labelProduit.setObjectName(_fromUtf8("labelProduit"))
        self.horizontalLayout_21.addWidget(self.labelProduit)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_21)
        spacerItem8 = QtGui.QSpacerItem(16777215, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem8)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_23 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_20.addWidget(self.label_23, QtCore.Qt.AlignHCenter)
        self.labelDate = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDate.sizePolicy().hasHeightForWidth())
        self.labelDate.setSizePolicy(sizePolicy)
        self.labelDate.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.labelDate.setObjectName(_fromUtf8("labelDate"))
        self.horizontalLayout_20.addWidget(self.labelDate)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_20)
        self.gridLayout_7.addLayout(self.horizontalLayout_23, 2, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_17.addWidget(self.label_17)
        self.labelClient = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelClient.sizePolicy().hasHeightForWidth())
        self.labelClient.setSizePolicy(sizePolicy)
        self.labelClient.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.labelClient.setObjectName(_fromUtf8("labelClient"))
        self.horizontalLayout_17.addWidget(self.labelClient)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_17)
        spacerItem9 = QtGui.QSpacerItem(16777215, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_16.addWidget(self.label_15, QtCore.Qt.AlignHCenter)
        self.labelCodeFac = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCodeFac.sizePolicy().hasHeightForWidth())
        self.labelCodeFac.setSizePolicy(sizePolicy)
        self.labelCodeFac.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelCodeFac.setStyleSheet(_fromUtf8("font-weight: bold;"))
        self.labelCodeFac.setObjectName(_fromUtf8("labelCodeFac"))
        self.horizontalLayout_16.addWidget(self.labelCodeFac)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_16)
        self.gridLayout_7.addLayout(self.horizontalLayout_22, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.toolBox.addItem(self.page_3, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.toolBox, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.stackedWidget.raise_()

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(2)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Select type of bill from box: ", None))
        self.cbBillType.setItemText(0, _translate("Dialog", "New", None))
        self.cbBillType.setItemText(1, _translate("Dialog", "New from Job", None))
        self.cbBillType.setItemText(2, _translate("Dialog", "New from Client", None))
        self.label_7.setText(_translate("Dialog", "Select style from box: ", None))
        self.cbBillStyle.setItemText(0, _translate("Dialog", "Kiwi Green", None))
        self.cbBillStyle.setItemText(1, _translate("Dialog", "Kiwi B&W", None))
        self.cbBillStyle.setItemText(2, _translate("Dialog", "Custom...", None))
        self.rbLatex.setText(_translate("Dialog", "LaTeX", None))
        self.rbWord.setText(_translate("Dialog", "MS Word", None))
        self.btnGenPreview.setText(_translate("Dialog", "Preview PDF", None))
        self.label_5.setText(_translate("Dialog", "Client", None))
        self.label_6.setText(_translate("Dialog", "Produit", None))
        self.label_2.setText(_translate("Dialog", "NUMERO FACTURE", None))
        self.label_3.setText(_translate("Dialog", "Ville:", None))
        self.label_4.setText(_translate("Dialog", "Le:", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Dialog", "Information", None))
        self.checkBox_5.setText(_translate("Dialog", "Set Font", None))
        self.label_14.setText(_translate("Dialog", "Size", None))
        self.checkBox_4.setText(_translate("Dialog", "Header Image", None))
        self.toolButton_2.setText(_translate("Dialog", "...", None))
        self.checkBox.setText(_translate("Dialog", "Footer Image", None))
        self.toolButton.setText(_translate("Dialog", "...", None))
        self.checkBox_3.setText(_translate("Dialog", "Header Text", None))
        self.checkBox_2.setText(_translate("Dialog", "Footer Text", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("Dialog", "Format", None))
        self.toolButton_3.setText(_translate("Dialog", "+", None))
        self.label_8.setText(_translate("Dialog", "Category", None))
        self.cbItemCat.setItemText(0, _translate("Dialog", "<Select Category>", None))
        self.cbItemCat.setItemText(1, _translate("Dialog", "Couverture Evenement", None))
        self.cbItemCat.setItemText(2, _translate("Dialog", "Shooting Photo", None))
        self.cbItemCat.setItemText(3, _translate("Dialog", "Shooting Video", None))
        self.cbItemCat.setItemText(4, _translate("Dialog", "Shooting Photo-Video", None))
        self.cbItemCat.setItemText(5, _translate("Dialog", "Packshot Produit", None))
        self.cbItemCat.setItemText(6, _translate("Dialog", "3D Conception (Stand)", None))
        self.cbItemCat.setItemText(7, _translate("Dialog", "3D Conception (Objet, Model, Structure)", None))
        self.cbItemCat.setItemText(8, _translate("Dialog", "2D Conception Logo", None))
        self.cbItemCat.setItemText(9, _translate("Dialog", "2D Conception Maquette (Vectoriel, Bitmap)", None))
        self.label_9.setText(_translate("Dialog", "Date Start", None))
        self.label_16.setText(_translate("Dialog", "Date End", None))
        self.label_10.setText(_translate("Dialog", "Description", None))
        self.leItemDescription.setText(_translate("Dialog", "<Description>", None))
        self.label_11.setText(_translate("Dialog", "Quantity", None))
        self.label_12.setText(_translate("Dialog", "Price/Unit", None))
        self.leItemUnitPrice.setText(_translate("Dialog", "<Description>", None))
        self.btnAddInvoiceItem.setText(_translate("Dialog", "Add", None))
        self.btnEditInvoiceItem.setText(_translate("Dialog", "Edit", None))
        self.btnDelInvoiceItem.setText(_translate("Dialog", "Delete", None))
        self.pushButton_3.setText(_translate("Dialog", "PushButton", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_7), _translate("Dialog", "Items", None))
        self.label_30.setText(_translate("Dialog", "Montant", None))
        self.label_27.setText(_translate("Dialog", "Designation", None))
        self.label_29.setText(_translate("Dialog", "Prix Unitaire", None))
        self.label_28.setText(_translate("Dialog", "Quantiite", None))
        self.label_25.setText(_translate("Dialog", "Produit:", None))
        self.labelProduit.setText(_translate("Dialog", "CCC", None))
        self.label_23.setText(_translate("Dialog", "Alger le:", None))
        self.labelDate.setText(_translate("Dialog", "12/12/2016", None))
        self.label_17.setText(_translate("Dialog", "Client:", None))
        self.labelClient.setText(_translate("Dialog", "AAA", None))
        self.label_15.setText(_translate("Dialog", "Numero Facture:", None))
        self.labelCodeFac.setText(_translate("Dialog", "000", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Dialog", "Preview", None))

import compiled_resources

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

